### ISSUE TITLE
Interchange Extract Bug

### ISSUE THREAD

**Issue by Djmeowzle** [refringe/OpenExtracts#1]
Loaded into an interchange raid and went about my business running around, looting stashes, and when i went to look at my extracts, all of them have the ??:??:?? of "timed extracts" and none of them are open/available. I have no other mods interfering or changing extracts/requirements, only raid times.

**Comment by refringe** [comment]
This would have been resolved with [v1.1.0](https://github.com/refringe/OpenExtracts/releases/tag/v1.1.0). Thanks for the report!
