### ISSUE TITLE
[Bug]: Cannot edit config file

### ISSUE THREAD

**Issue by jso19usa** [refringe/OpenExtracts#4]
### What happened?

I followed the installation instructions as written, however, I can't edit the config file without it being forcefully converted into another file type. Serris wont open it, notepad wont save it as anything but a text doc, and the json editor I have wont save it as anything but a plain text doc. Ive tried running the mod with the other file types, but it wont run the mod unless the file is a json file, and the only way I can get it to stay as a json file is if I dont edit it at all. Is there a particular editor I should be using, or is it a system issue on my end?

### SPT Version

master

### Server Log

```shell
unless its saved as a json file, it shows up in the server as a config load error
```

**Comment by refringe** [comment]
Sorry about the delay. This is simply an issue with the extension being changed from the expected `.json5` format. If you're using a basic text editor like Notepad, ensure that the extension type is changed to `*.*`, like this:

![Change Extension Type](https://i.imgur.com/6uVJA0x.png)

If you don't, the file ends up named `config.json5.txt` and it won't load.

You can also show full file names in Windows by enabling the following option:

![Enable Full File Names](https://i.imgur.com/FLbuIMt.png)
